name: Application Tests
on: [push,pull_request]
env:
  BUNDLE_PATH: vendor/bundle
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rubygems: [2.6.10, latest]
    services:
      database:
        image: postgres:9.6
        ports:
          - "5432:5432"
      cache:
        image: memcached
        ports:
          - "11211:11211"
      search:
        image: elasticsearch:5
        env:
          http.host: 0.0.0.0
          transport.host: 127.0.0.1
          xpack.security.enabled: false
          discovery.type: single-node
        ports:
          - "9200:9200"
        options: >-
          --health-cmd "curl --silent --fail localhost:9200/_cluster/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: Set Up Ruby
        uses: eregon/use-ruby-action@v1
        with:
          ruby-version: 2.6.5
      - name: Download Cached Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundler-cache-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundler-cache-
      - name: Setup Application
        run: |
          sudo apt-get update -qq
          sudo apt-get -yqq install libpq-dev chromium-chromedriver
          sh -c "if [ '${{ matrix.rubygems }}' != 'latest' ]; then gem update --system=${{ matrix.rubygems }}; fi"
          gem install bundler-audit:0.6.1 bundler --no-doc
          bundle install --jobs=3 --retry=3
          bundle audit update
          cp config/database.yml.example config/database.yml
          bundle exec rake db:create db:migrate db:test:prepare
      - name: Run Tests & Linting
        env:
          RUBYGEMS_VERSION: ${{ matrix.rubygems }}
        run: |
          bundle exec rails test
          bundle exec rake rubocop
          bundle audit check
          bundle exec brakeman
          script/build_docker.sh