name: Application Tests (ruby-head)
on: [push,pull_request]
env:
  BUNDLE_ENV: vendor/bundle
jobs:
  build:
    runs-on: ubuntu-latest
    container: rubylang/ruby:master-nightly-bionic
    services:
      database:
        image: postgres:9.6
        ports:
          - "5432:5432"
      cache:
        image: memcached
        ports:
          - "11211:11211"
      search:
        image: elasticsearch:5
        env:
          http.host: 0.0.0.0
          transport.host: 127.0.0.1
          xpack.security.enabled: false
          discovery.type: single-node
        ports:
          - "9200:9200"
        options: >-
          --health-cmd "curl --silent --fail localhost:9200/_cluster/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: Download Cached Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundler-cache-ruby-dev-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundler-cache-ruby-dev-
      - name: Setup Application
        run: |
          apt-get update -qq
          apt-get -yqq install libpq-dev chromium-chromedriver build-essential nodejs
          gem install bundler-audit:0.6.1 bundler --no-doc
          bundle install --jobs=3 --retry=3
          bundle audit update
          cp config/database.yml.example config/database.yml
          bundle exec rake db:create db:migrate db:test:prepare
      - name: Run Linting
        continue-on-error: true
        run: |
          bundle audit check
          bundle exec brakeman
          bundle exec rake rubocop
      - name: Run Tests
        continue-on-error: true
        run: |
          bundle exec rake test